import action from './actionCreator';

export const GET_DASHBOARD_DATA_REQUEST =
  'DASHBOARD/GET_DASHBOARD_DATA_REQUEST';
export const GET_DASHBOARD_DATA_SUCCESS =
  'DASHBOARD/GET_DASHBOARD_DATA_SUCCESS';
export const GET_DASHBOARD_DATA_FAILURE =
  'DASHBOARD/GET_DASHBOARD_DATA_FAILURE';

export const GET_INFORMATION_REQUEST = 'DASHBOARD/GET_INFORMATION_REQUEST';
export const GET_INFORMATION_SUCCESS = 'DASHBOARD/GET_INFORMATION_SUCCESS';
export const GET_INFORMATION_FAILURE = 'DASHBOARD/GET_INFORMATION_FAILURE';

export const getInformationRequest = action(GET_INFORMATION_REQUEST, 'params');

export const getDashboardDataRequest = action(GET_DASHBOARD_DATA_REQUEST);
