import action from './actionCreator';

export const GET_NOTIFICATIONS_REQUEST =
  'NOTIFICATIONS/GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS =
  'NOTIFICATIONS/GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE =
  'NOTIFICATIONS/GET_NOTIFICATIONS_FAILURE';

export const GET_INFORMATION_REQUEST = 'NOTIFICATIONS/GET_INFORMATION_REQUEST';
export const GET_INFORMATION_SUCCESS = 'NOTIFICATIONS/GET_INFORMATION_SUCCESS';
export const GET_INFORMATION_FAILURE = 'NOTIFICATIONS/GET_INFORMATION_FAILURE';

export const getInformationRequest = action(GET_INFORMATION_REQUEST, 'params');

export const getNotificationsRequest = action(
  GET_NOTIFICATIONS_REQUEST,
  'params',
);
